module.exports = {
    REGISTRAR_FEES: 1 * 10 ** 18,
    INVALID_REGISTRAR_FEES: 1 * 10 ** 15,
    GAS_LIMIT: 6721975,
    // GAS_LIMIT: 600000000,
    HANDLENAME_FEES: 1 * 10 ** 18,
    INVALID_HANDLENAME_FEES: 1 * 10 ** 15,
    INVALID_REGISTRAR_NAME_1: 'reg',
    INVALID_REGISTRAR_NAME_2: 'registrarnamewithlengthgreaterthansixteen',
    UNREGISTERED_REGISTRAR: 'registrar',
    VALID_REGISTRAR_NAME_1: 'validregistrar1',
    VALID_REGISTRAR_NAME_UPPER_2: 'VALIDREGISTRAR1',
    VALID_REGISTRAR_NAME_2: 'validregistrar2',
    VALID_REGISTRAR_NAME_3: 'validregistrar3',
    VALID_REGISTRAR_NAME_4: 'validregistrar4',
    VALID_REGISTRAR_NAME_5: 'validregistrar5',
    VALID_REGISTRAR_NAME_6: 'validregistrar6',
    UNREGISTERED_HANDLENAME: 'handlename',
    VALID_HANDLENAME_1: 'validhandlename1',
    VALID_HANDLENAME_2: 'validhandlename2',
    VALID_HANDLENAME_3: 'validhandlename3',
    VALID_HANDLENAME_4: 'validhandlename4',
    INVALID_HANDLENAME_1: 'h@nd!en@me',
    INVALID_HANDLENAME_3: 'hn',
    INVALID_HANDLENAME_4: 'invalidhandlenamefour',
    INDEX_1: 1,
    INVALID_INDEX_1: 0,
    COIN_NAME_1: 'bitcoin',
    INVALID_COIN_NAME_1: 'b!tco!n',
    COIN_ALIAS_1: 'btc',
    INVALID_COIN_ALIAS_1: '#btc',
    INDEX_2: 2,
    COIN_NAME_2: 'Ethereum',
    COIN_ALIAS_2: 'ETH',
    OTHER_COIN_ADDRESS_1: '3hqh1qgaqnwppbrvygjnrxnejcukd4e6ea',
    OTHER_COIN_ADDRESS_2: '2dFe1c2eqNWPr6yb3k6npLkbY80KD45rEy',
    INVALID_OTHER_COIN_ADDRESS_1: '2dFe1c2eqNWPr6yb3k6n',
    INVALID_INDEX: 9,
    BID_1: 1 * 10 ** 18,
    BID_2: 1.5 * 10 ** 18,
    BID_4: 1 * 10 ** 18,
    BLANK_ADDRESS: '0x0000000000000000000000000000000000000000',
}